version: '3'

networks:
  default: ~
services:
  app:
    build: ./doc
    volumes:
      - ./app:/app
    networks:
      - default
  redis:
    image: "redis"
    expose:
      - 6379
    networks:
      - default

